// Generated by svd2swift.

import MMIO

/// General Purpose Input/Output
public nonisolated(unsafe) let gpio = GPIO(unsafeAddress: 0x60091000)

/// Input/Output Multiplexer
public nonisolated(unsafe) let io_mux = IO_MUX(unsafeAddress: 0x60090000)

/// System Timer
public nonisolated(unsafe) let systimer = SYSTIMER(unsafeAddress: 0x6000a000)

/// Full-speed USB Serial/JTAG Controller
public nonisolated(unsafe) let usb_device = USB_DEVICE(unsafeAddress: 0x6000f000)
