// Generated by svd2swift.

import MMIO

/// Full-speed USB Serial/JTAG Controller
@RegisterBlock
public struct USB_DEVICE {
    /// FIFO access for the CDC-ACM data IN and OUT endpoints.
    @RegisterBlock(offset: 0x0)
    public var ep1: Register<EP1>

    /// Configuration and control registers for the CDC-ACM FIFOs.
    @RegisterBlock(offset: 0x4)
    public var ep1_conf: Register<EP1_CONF>

    /// Interrupt raw status register.
    @RegisterBlock(offset: 0x8)
    public var int_raw: Register<INT_RAW>

    /// Interrupt status register.
    @RegisterBlock(offset: 0xc)
    public var int_st: Register<INT_ST>

    /// Interrupt enable status register.
    @RegisterBlock(offset: 0x10)
    public var int_ena: Register<INT_ENA>

    /// Interrupt clear status register.
    @RegisterBlock(offset: 0x14)
    public var int_clr: Register<INT_CLR>

    /// PHY hardware configuration.
    @RegisterBlock(offset: 0x18)
    public var conf0: Register<CONF0>

    /// Registers used for debugging the PHY.
    @RegisterBlock(offset: 0x1c)
    public var test: Register<TEST>

    /// JTAG FIFO status and control registers.
    @RegisterBlock(offset: 0x20)
    public var jfifo_st: Register<JFIFO_ST>

    /// Last received SOF frame index register.
    @RegisterBlock(offset: 0x24)
    public var fram_num: Register<FRAM_NUM>

    /// Control IN endpoint status information.
    @RegisterBlock(offset: 0x28)
    public var in_ep0_st: Register<IN_EP0_ST>

    /// CDC-ACM IN endpoint status information.
    @RegisterBlock(offset: 0x2c)
    public var in_ep1_st: Register<IN_EP1_ST>

    /// CDC-ACM interrupt IN endpoint status information.
    @RegisterBlock(offset: 0x30)
    public var in_ep2_st: Register<IN_EP2_ST>

    /// JTAG IN endpoint status information.
    @RegisterBlock(offset: 0x34)
    public var in_ep3_st: Register<IN_EP3_ST>

    /// Control OUT endpoint status information.
    @RegisterBlock(offset: 0x38)
    public var out_ep0_st: Register<OUT_EP0_ST>

    /// CDC-ACM OUT endpoint status information.
    @RegisterBlock(offset: 0x3c)
    public var out_ep1_st: Register<OUT_EP1_ST>

    /// JTAG OUT endpoint status information.
    @RegisterBlock(offset: 0x40)
    public var out_ep2_st: Register<OUT_EP2_ST>

    /// Clock enable control
    @RegisterBlock(offset: 0x44)
    public var misc_conf: Register<MISC_CONF>

    /// Memory power control
    @RegisterBlock(offset: 0x48)
    public var mem_conf: Register<MEM_CONF>

    /// CDC-ACM chip reset control.
    @RegisterBlock(offset: 0x4c)
    public var chip_rst: Register<CHIP_RST>

    /// W0 of SET_LINE_CODING command.
    @RegisterBlock(offset: 0x50)
    public var set_line_code_w0: Register<SET_LINE_CODE_W0>

    /// W1 of SET_LINE_CODING command.
    @RegisterBlock(offset: 0x54)
    public var set_line_code_w1: Register<SET_LINE_CODE_W1>

    /// W0 of GET_LINE_CODING command.
    @RegisterBlock(offset: 0x58)
    public var get_line_code_w0: Register<GET_LINE_CODE_W0>

    /// W1 of GET_LINE_CODING command.
    @RegisterBlock(offset: 0x5c)
    public var get_line_code_w1: Register<GET_LINE_CODE_W1>

    /// Configuration registers' value update
    @RegisterBlock(offset: 0x60)
    public var config_update: Register<CONFIG_UPDATE>

    /// Serial AFIFO configure register
    @RegisterBlock(offset: 0x64)
    public var ser_afifo_config: Register<SER_AFIFO_CONFIG>

    /// USB Bus reset status register
    @RegisterBlock(offset: 0x68)
    public var bus_reset_st: Register<BUS_RESET_ST>

    /// Date register
    @RegisterBlock(offset: 0x80)
    public var date: Register<DATE>
}

extension USB_DEVICE {
    /// FIFO access for the CDC-ACM data IN and OUT endpoints.
    @Register(bitWidth: 32)
    public struct EP1 {
        /// Write and read byte data to/from UART Tx/Rx FIFO through this field. When USB_DEVICE_SERIAL_IN_EMPTY_INT is set, then user can write data (up to 64 bytes) into UART Tx FIFO. When USB_DEVICE_SERIAL_OUT_RECV_PKT_INT is set, user can check USB_DEVICE_OUT_EP1_WR_ADDR USB_DEVICE_OUT_EP0_RD_ADDR to know how many data is received, then read data from UART Rx FIFO.
        @ReadWrite(bits: 0..<8)
        public var rdwr_byte: RDWR_BYTE
    }

    /// Configuration and control registers for the CDC-ACM FIFOs.
    @Register(bitWidth: 32)
    public struct EP1_CONF {
        /// Set this bit to indicate writing byte data to UART Tx FIFO is done.
        @WriteOnly(bits: 0..<1)
        public var wr_done: WR_DONE

        /// 1'b1: Indicate UART Tx FIFO is not full and can write data into in. After writing USB_DEVICE_WR_DONE, this bit would be 0 until data in UART Tx FIFO is read by USB Host.
        @ReadOnly(bits: 1..<2)
        public var serial_in_ep_data_free: SERIAL_IN_EP_DATA_FREE

        /// 1'b1: Indicate there is data in UART Rx FIFO.
        @ReadOnly(bits: 2..<3)
        public var serial_out_ep_data_avail: SERIAL_OUT_EP_DATA_AVAIL
    }

    /// Interrupt raw status register.
    @Register(bitWidth: 32)
    public struct INT_RAW {
        /// The raw interrupt bit turns to high level when flush cmd is received for IN endpoint 2 of JTAG.
        @ReadWrite(bits: 0..<1)
        public var jtag_in_flush_int_raw: JTAG_IN_FLUSH_INT_RAW

        /// The raw interrupt bit turns to high level when SOF frame is received.
        @ReadWrite(bits: 1..<2)
        public var sof_int_raw: SOF_INT_RAW

        /// The raw interrupt bit turns to high level when Serial Port OUT Endpoint received one packet.
        @ReadWrite(bits: 2..<3)
        public var serial_out_recv_pkt_int_raw: SERIAL_OUT_RECV_PKT_INT_RAW

        /// The raw interrupt bit turns to high level when Serial Port IN Endpoint is empty.
        @ReadWrite(bits: 3..<4)
        public var serial_in_empty_int_raw: SERIAL_IN_EMPTY_INT_RAW

        /// The raw interrupt bit turns to high level when pid error is detected.
        @ReadWrite(bits: 4..<5)
        public var pid_err_int_raw: PID_ERR_INT_RAW

        /// The raw interrupt bit turns to high level when CRC5 error is detected.
        @ReadWrite(bits: 5..<6)
        public var crc5_err_int_raw: CRC5_ERR_INT_RAW

        /// The raw interrupt bit turns to high level when CRC16 error is detected.
        @ReadWrite(bits: 6..<7)
        public var crc16_err_int_raw: CRC16_ERR_INT_RAW

        /// The raw interrupt bit turns to high level when stuff error is detected.
        @ReadWrite(bits: 7..<8)
        public var stuff_err_int_raw: STUFF_ERR_INT_RAW

        /// The raw interrupt bit turns to high level when IN token for IN endpoint 1 is received.
        @ReadWrite(bits: 8..<9)
        public var in_token_rec_in_ep1_int_raw: IN_TOKEN_REC_IN_EP1_INT_RAW

        /// The raw interrupt bit turns to high level when usb bus reset is detected.
        @ReadWrite(bits: 9..<10)
        public var usb_bus_reset_int_raw: USB_BUS_RESET_INT_RAW

        /// The raw interrupt bit turns to high level when OUT endpoint 1 received packet with zero palyload.
        @ReadWrite(bits: 10..<11)
        public var out_ep1_zero_payload_int_raw: OUT_EP1_ZERO_PAYLOAD_INT_RAW

        /// The raw interrupt bit turns to high level when OUT endpoint 2 received packet with zero palyload.
        @ReadWrite(bits: 11..<12)
        public var out_ep2_zero_payload_int_raw: OUT_EP2_ZERO_PAYLOAD_INT_RAW

        /// The raw interrupt bit turns to high level when level of RTS from usb serial channel is changed.
        @ReadWrite(bits: 12..<13)
        public var rts_chg_int_raw: RTS_CHG_INT_RAW

        /// The raw interrupt bit turns to high level when level of DTR from usb serial channel is changed.
        @ReadWrite(bits: 13..<14)
        public var dtr_chg_int_raw: DTR_CHG_INT_RAW

        /// The raw interrupt bit turns to high level when level of GET LINE CODING request is received.
        @ReadWrite(bits: 14..<15)
        public var get_line_code_int_raw: GET_LINE_CODE_INT_RAW

        /// The raw interrupt bit turns to high level when level of SET LINE CODING request is received.
        @ReadWrite(bits: 15..<16)
        public var set_line_code_int_raw: SET_LINE_CODE_INT_RAW
    }

    /// Interrupt status register.
    @Register(bitWidth: 32)
    public struct INT_ST {
        /// The raw interrupt status bit for the USB_DEVICE_JTAG_IN_FLUSH_INT interrupt.
        @ReadOnly(bits: 0..<1)
        public var jtag_in_flush_int_st: JTAG_IN_FLUSH_INT_ST

        /// The raw interrupt status bit for the USB_DEVICE_SOF_INT interrupt.
        @ReadOnly(bits: 1..<2)
        public var sof_int_st: SOF_INT_ST

        /// The raw interrupt status bit for the USB_DEVICE_SERIAL_OUT_RECV_PKT_INT interrupt.
        @ReadOnly(bits: 2..<3)
        public var serial_out_recv_pkt_int_st: SERIAL_OUT_RECV_PKT_INT_ST

        /// The raw interrupt status bit for the USB_DEVICE_SERIAL_IN_EMPTY_INT interrupt.
        @ReadOnly(bits: 3..<4)
        public var serial_in_empty_int_st: SERIAL_IN_EMPTY_INT_ST

        /// The raw interrupt status bit for the USB_DEVICE_PID_ERR_INT interrupt.
        @ReadOnly(bits: 4..<5)
        public var pid_err_int_st: PID_ERR_INT_ST

        /// The raw interrupt status bit for the USB_DEVICE_CRC5_ERR_INT interrupt.
        @ReadOnly(bits: 5..<6)
        public var crc5_err_int_st: CRC5_ERR_INT_ST

        /// The raw interrupt status bit for the USB_DEVICE_CRC16_ERR_INT interrupt.
        @ReadOnly(bits: 6..<7)
        public var crc16_err_int_st: CRC16_ERR_INT_ST

        /// The raw interrupt status bit for the USB_DEVICE_STUFF_ERR_INT interrupt.
        @ReadOnly(bits: 7..<8)
        public var stuff_err_int_st: STUFF_ERR_INT_ST

        /// The raw interrupt status bit for the USB_DEVICE_IN_TOKEN_REC_IN_EP1_INT interrupt.
        @ReadOnly(bits: 8..<9)
        public var in_token_rec_in_ep1_int_st: IN_TOKEN_REC_IN_EP1_INT_ST

        /// The raw interrupt status bit for the USB_DEVICE_USB_BUS_RESET_INT interrupt.
        @ReadOnly(bits: 9..<10)
        public var usb_bus_reset_int_st: USB_BUS_RESET_INT_ST

        /// The raw interrupt status bit for the USB_DEVICE_OUT_EP1_ZERO_PAYLOAD_INT interrupt.
        @ReadOnly(bits: 10..<11)
        public var out_ep1_zero_payload_int_st: OUT_EP1_ZERO_PAYLOAD_INT_ST

        /// The raw interrupt status bit for the USB_DEVICE_OUT_EP2_ZERO_PAYLOAD_INT interrupt.
        @ReadOnly(bits: 11..<12)
        public var out_ep2_zero_payload_int_st: OUT_EP2_ZERO_PAYLOAD_INT_ST

        /// The raw interrupt status bit for the USB_DEVICE_RTS_CHG_INT interrupt.
        @ReadOnly(bits: 12..<13)
        public var rts_chg_int_st: RTS_CHG_INT_ST

        /// The raw interrupt status bit for the USB_DEVICE_DTR_CHG_INT interrupt.
        @ReadOnly(bits: 13..<14)
        public var dtr_chg_int_st: DTR_CHG_INT_ST

        /// The raw interrupt status bit for the USB_DEVICE_GET_LINE_CODE_INT interrupt.
        @ReadOnly(bits: 14..<15)
        public var get_line_code_int_st: GET_LINE_CODE_INT_ST

        /// The raw interrupt status bit for the USB_DEVICE_SET_LINE_CODE_INT interrupt.
        @ReadOnly(bits: 15..<16)
        public var set_line_code_int_st: SET_LINE_CODE_INT_ST
    }

    /// Interrupt enable status register.
    @Register(bitWidth: 32)
    public struct INT_ENA {
        /// The interrupt enable bit for the USB_DEVICE_JTAG_IN_FLUSH_INT interrupt.
        @ReadWrite(bits: 0..<1)
        public var jtag_in_flush_int_ena: JTAG_IN_FLUSH_INT_ENA

        /// The interrupt enable bit for the USB_DEVICE_SOF_INT interrupt.
        @ReadWrite(bits: 1..<2)
        public var sof_int_ena: SOF_INT_ENA

        /// The interrupt enable bit for the USB_DEVICE_SERIAL_OUT_RECV_PKT_INT interrupt.
        @ReadWrite(bits: 2..<3)
        public var serial_out_recv_pkt_int_ena: SERIAL_OUT_RECV_PKT_INT_ENA

        /// The interrupt enable bit for the USB_DEVICE_SERIAL_IN_EMPTY_INT interrupt.
        @ReadWrite(bits: 3..<4)
        public var serial_in_empty_int_ena: SERIAL_IN_EMPTY_INT_ENA

        /// The interrupt enable bit for the USB_DEVICE_PID_ERR_INT interrupt.
        @ReadWrite(bits: 4..<5)
        public var pid_err_int_ena: PID_ERR_INT_ENA

        /// The interrupt enable bit for the USB_DEVICE_CRC5_ERR_INT interrupt.
        @ReadWrite(bits: 5..<6)
        public var crc5_err_int_ena: CRC5_ERR_INT_ENA

        /// The interrupt enable bit for the USB_DEVICE_CRC16_ERR_INT interrupt.
        @ReadWrite(bits: 6..<7)
        public var crc16_err_int_ena: CRC16_ERR_INT_ENA

        /// The interrupt enable bit for the USB_DEVICE_STUFF_ERR_INT interrupt.
        @ReadWrite(bits: 7..<8)
        public var stuff_err_int_ena: STUFF_ERR_INT_ENA

        /// The interrupt enable bit for the USB_DEVICE_IN_TOKEN_REC_IN_EP1_INT interrupt.
        @ReadWrite(bits: 8..<9)
        public var in_token_rec_in_ep1_int_ena: IN_TOKEN_REC_IN_EP1_INT_ENA

        /// The interrupt enable bit for the USB_DEVICE_USB_BUS_RESET_INT interrupt.
        @ReadWrite(bits: 9..<10)
        public var usb_bus_reset_int_ena: USB_BUS_RESET_INT_ENA

        /// The interrupt enable bit for the USB_DEVICE_OUT_EP1_ZERO_PAYLOAD_INT interrupt.
        @ReadWrite(bits: 10..<11)
        public var out_ep1_zero_payload_int_ena: OUT_EP1_ZERO_PAYLOAD_INT_ENA

        /// The interrupt enable bit for the USB_DEVICE_OUT_EP2_ZERO_PAYLOAD_INT interrupt.
        @ReadWrite(bits: 11..<12)
        public var out_ep2_zero_payload_int_ena: OUT_EP2_ZERO_PAYLOAD_INT_ENA

        /// The interrupt enable bit for the USB_DEVICE_RTS_CHG_INT interrupt.
        @ReadWrite(bits: 12..<13)
        public var rts_chg_int_ena: RTS_CHG_INT_ENA

        /// The interrupt enable bit for the USB_DEVICE_DTR_CHG_INT interrupt.
        @ReadWrite(bits: 13..<14)
        public var dtr_chg_int_ena: DTR_CHG_INT_ENA

        /// The interrupt enable bit for the USB_DEVICE_GET_LINE_CODE_INT interrupt.
        @ReadWrite(bits: 14..<15)
        public var get_line_code_int_ena: GET_LINE_CODE_INT_ENA

        /// The interrupt enable bit for the USB_DEVICE_SET_LINE_CODE_INT interrupt.
        @ReadWrite(bits: 15..<16)
        public var set_line_code_int_ena: SET_LINE_CODE_INT_ENA
    }

    /// Interrupt clear status register.
    @Register(bitWidth: 32)
    public struct INT_CLR {
        /// Set this bit to clear the USB_DEVICE_JTAG_IN_FLUSH_INT interrupt.
        @WriteOnly(bits: 0..<1)
        public var jtag_in_flush_int_clr: JTAG_IN_FLUSH_INT_CLR

        /// Set this bit to clear the USB_DEVICE_JTAG_SOF_INT interrupt.
        @WriteOnly(bits: 1..<2)
        public var sof_int_clr: SOF_INT_CLR

        /// Set this bit to clear the USB_DEVICE_SERIAL_OUT_RECV_PKT_INT interrupt.
        @WriteOnly(bits: 2..<3)
        public var serial_out_recv_pkt_int_clr: SERIAL_OUT_RECV_PKT_INT_CLR

        /// Set this bit to clear the USB_DEVICE_SERIAL_IN_EMPTY_INT interrupt.
        @WriteOnly(bits: 3..<4)
        public var serial_in_empty_int_clr: SERIAL_IN_EMPTY_INT_CLR

        /// Set this bit to clear the USB_DEVICE_PID_ERR_INT interrupt.
        @WriteOnly(bits: 4..<5)
        public var pid_err_int_clr: PID_ERR_INT_CLR

        /// Set this bit to clear the USB_DEVICE_CRC5_ERR_INT interrupt.
        @WriteOnly(bits: 5..<6)
        public var crc5_err_int_clr: CRC5_ERR_INT_CLR

        /// Set this bit to clear the USB_DEVICE_CRC16_ERR_INT interrupt.
        @WriteOnly(bits: 6..<7)
        public var crc16_err_int_clr: CRC16_ERR_INT_CLR

        /// Set this bit to clear the USB_DEVICE_STUFF_ERR_INT interrupt.
        @WriteOnly(bits: 7..<8)
        public var stuff_err_int_clr: STUFF_ERR_INT_CLR

        /// Set this bit to clear the USB_DEVICE_IN_TOKEN_IN_EP1_INT interrupt.
        @WriteOnly(bits: 8..<9)
        public var in_token_rec_in_ep1_int_clr: IN_TOKEN_REC_IN_EP1_INT_CLR

        /// Set this bit to clear the USB_DEVICE_USB_BUS_RESET_INT interrupt.
        @WriteOnly(bits: 9..<10)
        public var usb_bus_reset_int_clr: USB_BUS_RESET_INT_CLR

        /// Set this bit to clear the USB_DEVICE_OUT_EP1_ZERO_PAYLOAD_INT interrupt.
        @WriteOnly(bits: 10..<11)
        public var out_ep1_zero_payload_int_clr: OUT_EP1_ZERO_PAYLOAD_INT_CLR

        /// Set this bit to clear the USB_DEVICE_OUT_EP2_ZERO_PAYLOAD_INT interrupt.
        @WriteOnly(bits: 11..<12)
        public var out_ep2_zero_payload_int_clr: OUT_EP2_ZERO_PAYLOAD_INT_CLR

        /// Set this bit to clear the USB_DEVICE_RTS_CHG_INT interrupt.
        @WriteOnly(bits: 12..<13)
        public var rts_chg_int_clr: RTS_CHG_INT_CLR

        /// Set this bit to clear the USB_DEVICE_DTR_CHG_INT interrupt.
        @WriteOnly(bits: 13..<14)
        public var dtr_chg_int_clr: DTR_CHG_INT_CLR

        /// Set this bit to clear the USB_DEVICE_GET_LINE_CODE_INT interrupt.
        @WriteOnly(bits: 14..<15)
        public var get_line_code_int_clr: GET_LINE_CODE_INT_CLR

        /// Set this bit to clear the USB_DEVICE_SET_LINE_CODE_INT interrupt.
        @WriteOnly(bits: 15..<16)
        public var set_line_code_int_clr: SET_LINE_CODE_INT_CLR
    }

    /// PHY hardware configuration.
    @Register(bitWidth: 32)
    public struct CONF0 {
        /// Select internal/external PHY
        @ReadWrite(bits: 0..<1)
        public var phy_sel: PHY_SEL

        /// Enable software control USB D+ D- exchange
        @ReadWrite(bits: 1..<2)
        public var exchg_pins_override: EXCHG_PINS_OVERRIDE

        /// USB D+ D- exchange
        @ReadWrite(bits: 2..<3)
        public var exchg_pins: EXCHG_PINS

        /// Control single-end input high threshold,1.76V to 2V, step 80mV
        @ReadWrite(bits: 3..<5)
        public var vrefh: VREFH

        /// Control single-end input low threshold,0.8V to 1.04V, step 80mV
        @ReadWrite(bits: 5..<7)
        public var vrefl: VREFL

        /// Enable software control input threshold
        @ReadWrite(bits: 7..<8)
        public var vref_override: VREF_OVERRIDE

        /// Enable software control USB D+ D- pullup pulldown
        @ReadWrite(bits: 8..<9)
        public var pad_pull_override: PAD_PULL_OVERRIDE

        /// Control USB D+ pull up.
        @ReadWrite(bits: 9..<10)
        public var dp_pullup: DP_PULLUP

        /// Control USB D+ pull down.
        @ReadWrite(bits: 10..<11)
        public var dp_pulldown: DP_PULLDOWN

        /// Control USB D- pull up.
        @ReadWrite(bits: 11..<12)
        public var dm_pullup: DM_PULLUP

        /// Control USB D- pull down.
        @ReadWrite(bits: 12..<13)
        public var dm_pulldown: DM_PULLDOWN

        /// Control pull up value.
        @ReadWrite(bits: 13..<14)
        public var pullup_value: PULLUP_VALUE

        /// Enable USB pad function.
        @ReadWrite(bits: 14..<15)
        public var usb_pad_enable: USB_PAD_ENABLE

        /// Set this bit usb_jtag, the connection between usb_jtag and internal JTAG is disconnected, and MTMS, MTDI, MTCK are output through GPIO Matrix, MTDO is input through GPIO Matrix.
        @ReadWrite(bits: 15..<16)
        public var usb_jtag_bridge_en: USB_JTAG_BRIDGE_EN
    }

    /// Registers used for debugging the PHY.
    @Register(bitWidth: 32)
    public struct TEST {
        /// Enable test of the USB pad
        @ReadWrite(bits: 0..<1)
        public var enable: ENABLE

        /// USB pad oen in test
        @ReadWrite(bits: 1..<2)
        public var usb_oe: USB_OE

        /// USB D+ tx value in test
        @ReadWrite(bits: 2..<3)
        public var tx_dp: TX_DP

        /// USB D- tx value in test
        @ReadWrite(bits: 3..<4)
        public var tx_dm: TX_DM

        /// USB RCV value in test
        @ReadOnly(bits: 4..<5)
        public var rx_rcv: RX_RCV

        /// USB D+ rx value in test
        @ReadOnly(bits: 5..<6)
        public var rx_dp: RX_DP

        /// USB D- rx value in test
        @ReadOnly(bits: 6..<7)
        public var rx_dm: RX_DM
    }

    /// JTAG FIFO status and control registers.
    @Register(bitWidth: 32)
    public struct JFIFO_ST {
        /// JTAT in fifo counter.
        @ReadOnly(bits: 0..<2)
        public var in_fifo_cnt: IN_FIFO_CNT

        /// 1: JTAG in fifo is empty.
        @ReadOnly(bits: 2..<3)
        public var in_fifo_empty: IN_FIFO_EMPTY

        /// 1: JTAG in fifo is full.
        @ReadOnly(bits: 3..<4)
        public var in_fifo_full: IN_FIFO_FULL

        /// JTAT out fifo counter.
        @ReadOnly(bits: 4..<6)
        public var out_fifo_cnt: OUT_FIFO_CNT

        /// 1: JTAG out fifo is empty.
        @ReadOnly(bits: 6..<7)
        public var out_fifo_empty: OUT_FIFO_EMPTY

        /// 1: JTAG out fifo is full.
        @ReadOnly(bits: 7..<8)
        public var out_fifo_full: OUT_FIFO_FULL

        /// Write 1 to reset JTAG in fifo.
        @ReadWrite(bits: 8..<9)
        public var in_fifo_reset: IN_FIFO_RESET

        /// Write 1 to reset JTAG out fifo.
        @ReadWrite(bits: 9..<10)
        public var out_fifo_reset: OUT_FIFO_RESET
    }

    /// Last received SOF frame index register.
    @Register(bitWidth: 32)
    public struct FRAM_NUM {
        /// Frame index of received SOF frame.
        @ReadOnly(bits: 0..<11)
        public var sof_frame_index: SOF_FRAME_INDEX
    }

    /// Control IN endpoint status information.
    @Register(bitWidth: 32)
    public struct IN_EP0_ST {
        /// State of IN Endpoint 0.
        @ReadOnly(bits: 0..<2)
        public var in_ep0_state: IN_EP0_STATE

        /// Write data address of IN endpoint 0.
        @ReadOnly(bits: 2..<9)
        public var in_ep0_wr_addr: IN_EP0_WR_ADDR

        /// Read data address of IN endpoint 0.
        @ReadOnly(bits: 9..<16)
        public var in_ep0_rd_addr: IN_EP0_RD_ADDR
    }

    /// CDC-ACM IN endpoint status information.
    @Register(bitWidth: 32)
    public struct IN_EP1_ST {
        /// State of IN Endpoint 1.
        @ReadOnly(bits: 0..<2)
        public var in_ep1_state: IN_EP1_STATE

        /// Write data address of IN endpoint 1.
        @ReadOnly(bits: 2..<9)
        public var in_ep1_wr_addr: IN_EP1_WR_ADDR

        /// Read data address of IN endpoint 1.
        @ReadOnly(bits: 9..<16)
        public var in_ep1_rd_addr: IN_EP1_RD_ADDR
    }

    /// CDC-ACM interrupt IN endpoint status information.
    @Register(bitWidth: 32)
    public struct IN_EP2_ST {
        /// State of IN Endpoint 2.
        @ReadOnly(bits: 0..<2)
        public var in_ep2_state: IN_EP2_STATE

        /// Write data address of IN endpoint 2.
        @ReadOnly(bits: 2..<9)
        public var in_ep2_wr_addr: IN_EP2_WR_ADDR

        /// Read data address of IN endpoint 2.
        @ReadOnly(bits: 9..<16)
        public var in_ep2_rd_addr: IN_EP2_RD_ADDR
    }

    /// JTAG IN endpoint status information.
    @Register(bitWidth: 32)
    public struct IN_EP3_ST {
        /// State of IN Endpoint 3.
        @ReadOnly(bits: 0..<2)
        public var in_ep3_state: IN_EP3_STATE

        /// Write data address of IN endpoint 3.
        @ReadOnly(bits: 2..<9)
        public var in_ep3_wr_addr: IN_EP3_WR_ADDR

        /// Read data address of IN endpoint 3.
        @ReadOnly(bits: 9..<16)
        public var in_ep3_rd_addr: IN_EP3_RD_ADDR
    }

    /// Control OUT endpoint status information.
    @Register(bitWidth: 32)
    public struct OUT_EP0_ST {
        /// State of OUT Endpoint 0.
        @ReadOnly(bits: 0..<2)
        public var out_ep0_state: OUT_EP0_STATE

        /// Write data address of OUT endpoint 0. When USB_DEVICE_SERIAL_OUT_RECV_PKT_INT is detected, there are USB_DEVICE_OUT_EP0_WR_ADDR-2 bytes data in OUT EP0.
        @ReadOnly(bits: 2..<9)
        public var out_ep0_wr_addr: OUT_EP0_WR_ADDR

        /// Read data address of OUT endpoint 0.
        @ReadOnly(bits: 9..<16)
        public var out_ep0_rd_addr: OUT_EP0_RD_ADDR
    }

    /// CDC-ACM OUT endpoint status information.
    @Register(bitWidth: 32)
    public struct OUT_EP1_ST {
        /// State of OUT Endpoint 1.
        @ReadOnly(bits: 0..<2)
        public var out_ep1_state: OUT_EP1_STATE

        /// Write data address of OUT endpoint 1. When USB_DEVICE_SERIAL_OUT_RECV_PKT_INT is detected, there are USB_DEVICE_OUT_EP1_WR_ADDR-2 bytes data in OUT EP1.
        @ReadOnly(bits: 2..<9)
        public var out_ep1_wr_addr: OUT_EP1_WR_ADDR

        /// Read data address of OUT endpoint 1.
        @ReadOnly(bits: 9..<16)
        public var out_ep1_rd_addr: OUT_EP1_RD_ADDR

        /// Data count in OUT endpoint 1 when one packet is received.
        @ReadOnly(bits: 16..<23)
        public var out_ep1_rec_data_cnt: OUT_EP1_REC_DATA_CNT
    }

    /// JTAG OUT endpoint status information.
    @Register(bitWidth: 32)
    public struct OUT_EP2_ST {
        /// State of OUT Endpoint 2.
        @ReadOnly(bits: 0..<2)
        public var out_ep2_state: OUT_EP2_STATE

        /// Write data address of OUT endpoint 2. When USB_DEVICE_SERIAL_OUT_RECV_PKT_INT is detected, there are USB_DEVICE_OUT_EP2_WR_ADDR-2 bytes data in OUT EP2.
        @ReadOnly(bits: 2..<9)
        public var out_ep2_wr_addr: OUT_EP2_WR_ADDR

        /// Read data address of OUT endpoint 2.
        @ReadOnly(bits: 9..<16)
        public var out_ep2_rd_addr: OUT_EP2_RD_ADDR
    }

    /// Clock enable control
    @Register(bitWidth: 32)
    public struct MISC_CONF {
        /// 1'h1: Force clock on for register. 1'h0: Support clock only when application writes registers.
        @ReadWrite(bits: 0..<1)
        public var clk_en: CLK_EN
    }

    /// Memory power control
    @Register(bitWidth: 32)
    public struct MEM_CONF {
        /// 1: power down usb memory.
        @ReadWrite(bits: 0..<1)
        public var usb_mem_pd: USB_MEM_PD

        /// 1: Force clock on for usb memory.
        @ReadWrite(bits: 1..<2)
        public var usb_mem_clk_en: USB_MEM_CLK_EN
    }

    /// CDC-ACM chip reset control.
    @Register(bitWidth: 32)
    public struct CHIP_RST {
        /// 1: Chip reset is detected from usb serial channel. Software write 1 to clear it.
        @ReadOnly(bits: 0..<1)
        public var rts: RTS

        /// 1: Chip reset is detected from usb jtag channel. Software write 1 to clear it.
        @ReadOnly(bits: 1..<2)
        public var dtr: DTR

        /// Set this bit to disable chip reset from usb serial channel to reset chip.
        @ReadWrite(bits: 2..<3)
        public var usb_uart_chip_rst_dis: USB_UART_CHIP_RST_DIS
    }

    /// W0 of SET_LINE_CODING command.
    @Register(bitWidth: 32)
    public struct SET_LINE_CODE_W0 {
        /// The value of dwDTERate set by host through SET_LINE_CODING command.
        @ReadOnly(bits: 0..<32)
        public var dw_dte_rate: DW_DTE_RATE
    }

    /// W1 of SET_LINE_CODING command.
    @Register(bitWidth: 32)
    public struct SET_LINE_CODE_W1 {
        /// The value of bCharFormat set by host through SET_LINE_CODING command.
        @ReadOnly(bits: 0..<8)
        public var bchar_format: BCHAR_FORMAT

        /// The value of bParityTpye set by host through SET_LINE_CODING command.
        @ReadOnly(bits: 8..<16)
        public var bparity_type: BPARITY_TYPE

        /// The value of bDataBits set by host through SET_LINE_CODING command.
        @ReadOnly(bits: 16..<24)
        public var bdata_bits: BDATA_BITS
    }

    /// W0 of GET_LINE_CODING command.
    @Register(bitWidth: 32)
    public struct GET_LINE_CODE_W0 {
        /// The value of dwDTERate set by software which is requested by GET_LINE_CODING command.
        @ReadWrite(bits: 0..<32)
        public var get_dw_dte_rate: GET_DW_DTE_RATE
    }

    /// W1 of GET_LINE_CODING command.
    @Register(bitWidth: 32)
    public struct GET_LINE_CODE_W1 {
        /// The value of bCharFormat set by software which is requested by GET_LINE_CODING command.
        @ReadWrite(bits: 0..<8)
        public var get_bdata_bits: GET_BDATA_BITS

        /// The value of bParityTpye set by software which is requested by GET_LINE_CODING command.
        @ReadWrite(bits: 8..<16)
        public var get_bparity_type: GET_BPARITY_TYPE

        /// The value of bDataBits set by software which is requested by GET_LINE_CODING command.
        @ReadWrite(bits: 16..<24)
        public var get_bchar_format: GET_BCHAR_FORMAT
    }

    /// Configuration registers' value update
    @Register(bitWidth: 32)
    public struct CONFIG_UPDATE {
        /// Write 1 to this register would update the value of configure registers from APB clock domain to 48MHz clock domain.
        @WriteOnly(bits: 0..<1)
        public var config_update_field: CONFIG_UPDATE_FIELD
    }

    /// Serial AFIFO configure register
    @Register(bitWidth: 32)
    public struct SER_AFIFO_CONFIG {
        /// Write 1 to reset CDC_ACM IN async FIFO write clock domain.
        @ReadWrite(bits: 0..<1)
        public var serial_in_afifo_reset_wr: SERIAL_IN_AFIFO_RESET_WR

        /// Write 1 to reset CDC_ACM IN async FIFO read clock domain.
        @ReadWrite(bits: 1..<2)
        public var serial_in_afifo_reset_rd: SERIAL_IN_AFIFO_RESET_RD

        /// Write 1 to reset CDC_ACM OUT async FIFO write clock domain.
        @ReadWrite(bits: 2..<3)
        public var serial_out_afifo_reset_wr: SERIAL_OUT_AFIFO_RESET_WR

        /// Write 1 to reset CDC_ACM OUT async FIFO read clock domain.
        @ReadWrite(bits: 3..<4)
        public var serial_out_afifo_reset_rd: SERIAL_OUT_AFIFO_RESET_RD

        /// CDC_ACM OUTOUT async FIFO empty signal in read clock domain.
        @ReadOnly(bits: 4..<5)
        public var serial_out_afifo_rempty: SERIAL_OUT_AFIFO_REMPTY

        /// CDC_ACM OUT IN async FIFO empty signal in write clock domain.
        @ReadOnly(bits: 5..<6)
        public var serial_in_afifo_wfull: SERIAL_IN_AFIFO_WFULL
    }

    /// USB Bus reset status register
    @Register(bitWidth: 32)
    public struct BUS_RESET_ST {
        /// USB bus reset status. 0: USB-Serial-JTAG is in usb bus reset status. 1: USB bus reset is released.
        @ReadOnly(bits: 0..<1)
        public var usb_bus_reset_st: USB_BUS_RESET_ST
    }

    /// Date register
    @Register(bitWidth: 32)
    public struct DATE {
        /// register version.
        @ReadWrite(bits: 0..<32)
        public var date_field: DATE_FIELD
    }
}
